[package]
name = "dummy"
version = "0.3.3"
authors = ["cksac <cs.cksac@gmail.com>"]
description = "Macros implementation of #[derive(Dummy)]"
keywords = ["faker", "data", "random"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/cksac/fake-rs"
homepage = "https://github.com/cksac/fake-rs"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
darling = "0.10"
